# reporter: json
disabled_rules:
  - todo # 開発中のみignore
excluded:
  - Carthage
  - Pods
  - vendor
line_length: 200
function_body_length:
  - 50 # 仮決め
  - 100
type_body_length:
  - 300 # 仮決め
  - 500
identifier_name:
  min_length: 1
